In [130]:
import pandas as pd
import numpy as np
import plotly.express as px

#DATA LOADING

In [131]:
df = pd.read_csv("Air_Quality.csv")
df.head()

,Unique ID,Indicator ID,Name,Measure,Measure Info,Geo Type Name,Geo Join ID,Geo Place Name,Time Period,Start_Date,Data Value,Message
0,172653,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,203,Bedford Stuyvesant - Crown Heights,Annual Average 2011,12/1/2010,25.30,NaN
1,172585,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,203,Bedford Stuyvesant - Crown Heights,Annual Average 2009,12/1/2008,26.93,NaN
2,336637,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,204,East New York,Annual Average 2015,1/1/2015,19.09,NaN
3,336622,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,103,Fordham - Bronx Pk,Annual Average 2015,1/1/2015,19.76,NaN
4,172582,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,104,Pelham - Throgs Neck,Annual Average 2009,12/1/2008,22.83,NaN

# DATA UNDERSTANDING

##Dataset Dimensions

In [132]:
df.shape

(16218, 12)

##Dataset Structure and Data Types

In [133]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16218 entries, 0 to 16217
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unique ID       16218 non-null  int64
 1   Indicator ID    16218 non-null  int64
 2   Name            16218 non-null  str
 3   Measure         16218 non-null  str
 4   Measure Info    16218 non-null  str
 5   Geo Type Name   16218 non-null  str
 6   Geo Join ID     16218 non-null  int64
 7   Geo Place Name  16218 non-null  str
 8   Time Period     16218 non-null  str
 9   Start_Date      16218 non-null  str
 10  Data Value      16218 non-null  float64
 11  Message         0 non-null      float64
dtypes: float64(2), int64(3), str(7)
memory usage: 2.8 MB

##Missing Values Assessment

In [134]:
df.isnull().sum()

Unique ID             0
Indicator ID          0
Name                  0
Measure               0
Measure Info          0
Geo Type Name         0
Geo Join ID           0
Geo Place Name        0
Time Period           0
Start_Date            0
Data Value            0
Message           16218
dtype: int64

##Duplicate Records Assessment

In [135]:
df.duplicated().sum()

np.int64(0)

##Unique ID Integrity Check

In [136]:
df["Unique ID"].duplicated().sum()

np.int64(0)

##Unique Values and Categories Exploration

In [137]:
for column in df.columns:
    print(f"\n--- {column} ---")
    print("Unique values:", df[column].nunique())
    print(df[column].unique()[:20])

--- Unique ID ---
Unique values: 16218
[172653 172585 336637 336622 172582 667327 172607 172675 175345 176689
 176682 336507 740910 175348 175894 175895 175349 176693 741006 550028]

--- Indicator ID ---
Unique values: 21
[375 365 386 648 643 657 661 650 640 651 641 642 644 645 652 659 655 653
 647 646]

--- Name ---
Unique values: 18
<ArrowStringArray>
[                                'Nitrogen dioxide (NO2)',
                                'Fine particles (PM 2.5)',
                                             'Ozone (O3)',
        'Asthma emergency department visits due to PM2.5',
                          'Annual vehicle miles traveled',
                   'Asthma hospitalizations due to Ozone',
    'Respiratory hospitalizations due to PM2.5 (age 20+)',
                  'Boiler Emissions- Total SO2 Emissions',
 'Cardiovascular hospitalizations due to PM2.5 (age 40+)',
                'Boiler Emissions- Total PM2.5 Emissions',
                  'Boiler Emissions- Total NOx Emissions',
                  'Annual vehicle miles travelled (cars)',
                'Annual vehicle miles travelled (trucks)',
            'Cardiac and respiratory deaths due to Ozone',
       'Asthma emergency departments visits due to Ozone',
                      'Outdoor Air Toxics - Formaldehyde',
                           'Outdoor Air Toxics - Benzene',
                                    'Deaths due to PM2.5']
Length: 18, dtype: str

--- Measure ---
Unique values: 8
<ArrowStringArray>
[                                'Mean',
 'Estimated annual rate (under age 18)',
                        'million miles',
      'Estimated annual rate (age 18+)',
                'Estimated annual rate',
                       'Number per km2',
         'Annual average concentration',
      'Estimated annual rate (age 30+)']
Length: 8, dtype: str

--- Measure Info ---
Unique values: 8
<ArrowStringArray>
[                 'ppb',               'mcg/m3', 'per 100,000 children',
              'per km2',   'per 100,000 adults',               'number',
          'per 100,000',                'µg/m3']
Length: 8, dtype: str

--- Geo Type Name ---
Unique values: 5
<ArrowStringArray>
['UHF34', 'UHF42', 'CD', 'Borough', 'Citywide']
Length: 5, dtype: str

--- Geo Join ID ---
Unique values: 72
[   203    204    103    104 306308    206    106    209    210    410
    201    101    102    402    301    107    207    208    407    302]

--- Geo Place Name ---
Unique values: 114
<ArrowStringArray>
['Bedford Stuyvesant - Crown Heights',                      'East New York',
                 'Fordham - Bronx Pk',               'Pelham - Throgs Neck',
                    'Chelsea-Village',                       'Borough Park',
           'High Bridge - Morrisania',            'Bensonhurst - Bay Ridge',
      'Coney Island - Sheepshead Bay',                          'Rockaways',
       'Mott Haven and Melrose (CD1)',           'Financial District (CD1)',
   'Greenwich Village and Soho (CD2)',       'Woodside and Sunnyside (CD2)',
                         'Greenpoint',            'Kingsbridge - Riverdale',
                    'Northeast Bronx',                        'West Queens',
                 'Washington Heights',           'Hunts Point - Mott Haven']
Length: 20, dtype: str

--- Time Period ---
Unique values: 50
<ArrowStringArray>
[            'Annual Average 2011',             'Annual Average 2009',
             'Annual Average 2015',             'Annual Average 2020',
                  'Winter 2010-11',             'Annual Average 2013',
                  'Winter 2014-15',             'Annual Average 2021',
                     'Summer 2009',             'Annual Average 2017',
                  'Winter 2009-10',                     'Summer 2017',
                     'Summer 2018',                  'Winter 2018-19',
                     'Summer 2014',                  'Winter 2016-17',
             'Annual Average 2014',                  'Winter 2011-12',
                     'Summer 2020', '2-Year Summer Average 2009-2010']
Length: 20, dtype: str

--- Start_Date ---
Unique values: 40
<ArrowStringArray>
[ '12/1/2010',  '12/1/2008',   '1/1/2015',   '1/1/2020',  '12/1/2012',
  '12/1/2014',   '1/1/2021',   '6/1/2009',   '1/1/2017',  '12/1/2009',
   '6/1/2017',   '6/1/2018',  '12/1/2018',   '6/1/2014',  '12/1/2016',
  '12/1/2013',  '12/1/2011',   '6/1/2020', '12/31/2015',   '1/1/2018']
Length: 20, dtype: str

--- Data Value ---
Unique values: 3649
[25.3  26.93 19.09 19.76 22.83 16.19 38.16 34.96 30.1  20.23 23.73 26.
 18.04 28.44 18.95 15.22 25.7  16.36 11.41 21.25]

--- Message ---
Unique values: 0
[nan]

##Categorical Variables Distribution

In [138]:
df["Name"].value_counts()

Name
Nitrogen dioxide (NO2)                                    5499
Fine particles (PM 2.5)                                   5499
Ozone (O3)                                                1974
Asthma emergency department visits due to PM2.5            384
Asthma hospitalizations due to Ozone                       384
Asthma emergency departments visits due to Ozone           384
Annual vehicle miles travelled (cars)                      214
Annual vehicle miles traveled                              209
Annual vehicle miles travelled (trucks)                    209
Outdoor Air Toxics - Formaldehyde                          203
Outdoor Air Toxics - Benzene                               203
Respiratory hospitalizations due to PM2.5 (age 20+)        192
Cardiovascular hospitalizations due to PM2.5 (age 40+)     192
Cardiac and respiratory deaths due to Ozone                192
Deaths due to PM2.5                                        192
Boiler Emissions- Total SO2 Emissions                       96
Boiler Emissions- Total PM2.5 Emissions                     96
Boiler Emissions- Total NOx Emissions                       96
Name: count, dtype: int64

In [139]:
df["Measure"].value_counts()

Measure
Mean                                    12972
million miles                             632
Estimated annual rate (under age 18)      576
Estimated annual rate (age 18+)           576
Estimated annual rate                     576
Annual average concentration              406
Number per km2                            288
Estimated annual rate (age 30+)           192
Name: count, dtype: int64

In [140]:
df["Measure Info"].value_counts()

Measure Info
ppb                     7473
mcg/m3                  5499
per 100,000 adults      1152
per km2                  632
per 100,000 children     576
µg/m3                    406
number                   288
per 100,000              192
Name: count, dtype: int64

In [141]:
df["Geo Type Name"].value_counts()

Geo Type Name
UHF42       6300
CD          5900
UHF34       3128
Borough      740
Citywide     150
Name: count, dtype: int64

In [142]:
df["Time Period"].value_counts()

Time Period
2012-2014                          480
2015-2017                          480
2009-2011                          480
2005-2007                          480
Summer 2009                        423
Summer 2017                        423
Summer 2018                        423
Summer 2014                        423
Summer 2020                        423
Summer 2013                        423
Summer 2021                        423
Summer 2012                        423
Summer 2016                        423
Summer 2010                        423
Summer 2011                        423
Summer 2015                        423
Summer 2019                        423
2005                               407
2016                               321
Annual Average 2011                282
Annual Average 2009                282
Annual Average 2015                282
Annual Average 2020                282
Winter 2010-11                     282
Annual Average 2013                282
Winter 2014-15                     282
Annual Average 2021                282
Annual Average 2017                282
Winter 2009-10                     282
Winter 2018-19                     282
Winter 2016-17                     282
Annual Average 2014                282
Winter 2011-12                     282
Annual Average 2016                282
Annual Average 2018                282
Winter 2008-09                     282
Winter 2017-18                     282
Winter 2013-14                     282
Annual Average 2019                282
Winter 2020-21                     282
Winter 2015-16                     282
Winter 2019-20                     282
Annual Average 2010                282
Winter 2012-13                     282
Annual Average 2012                282
2011                               214
2015                               144
2013                               144
2-Year Summer Average 2009-2010    141
2014                                96
Name: count, dtype: int64

##Data Value Statistical Summary

In [143]:
df["Data Value"].describe().round(2)

count    16218.00
mean        19.98
std         21.32
min          0.00
25%          9.05
50%         15.30
75%         26.04
max        424.70
Name: Data Value, dtype: float64

##Indicator and Measurement Unit Consistency Check

In [144]:
pd.crosstab(df["Name"], df["Measure Info"])

Measure Info,mcg/m3,number,"per 100,000","per 100,000 adults","per 100,000 children",per km2,ppb,µg/m3
Name,,,,,,,,
Annual vehicle miles traveled,0,0,0,0,0,209,0,0
Annual vehicle miles travelled (cars),0,0,0,0,0,214,0,0
Annual vehicle miles travelled (trucks),0,0,0,0,0,209,0,0
Asthma emergency department visits due to PM2.5,0,0,0,192,192,0,0,0
Asthma emergency departments visits due to Ozone,0,0,0,192,192,0,0,0
Asthma hospitalizations due to Ozone,0,0,0,192,192,0,0,0
Boiler Emissions- Total NOx Emissions,0,96,0,0,0,0,0,0
Boiler Emissions- Total PM2.5 Emissions,0,96,0,0,0,0,0,0
Boiler Emissions- Total SO2 Emissions,0,96,0,0,0,0,0,0
Cardiac and respiratory deaths due to Ozone,0,0,192,0,0,0,0,0
Cardiovascular hospitalizations due to PM2.5 (age 40+),0,0,0,192,0,0,0,0
Deaths due to PM2.5,0,0,0,192,0,0,0,0
Fine particles (PM 2.5),5499,0,0,0,0,0,0,0
Nitrogen dioxide (NO2),0,0,0,0,0,0,5499,0
Outdoor Air Toxics - Benzene,0,0,0,0,0,0,0,203
Outdoor Air Toxics - Formaldehyde,0,0,0,0,0,0,0,203
Ozone (O3),0,0,0,0,0,0,1974,0
Respiratory hospitalizations due to PM2.5 (age 20+),0,0,0,192,0,0,0,0

##Measure and Measurement Unit Consistency Check

In [145]:
pd.crosstab(df["Measure"], df["Measure Info"])

Measure Info,mcg/m3,number,"per 100,000","per 100,000 adults","per 100,000 children",per km2,ppb,µg/m3
Measure,,,,,,,,
Annual average concentration,0,0,0,0,0,0,0,406
Estimated annual rate,0,0,192,384,0,0,0,0
Estimated annual rate (age 18+),0,0,0,576,0,0,0,0
Estimated annual rate (age 30+),0,0,0,192,0,0,0,0
Estimated annual rate (under age 18),0,0,0,0,576,0,0,0
Mean,5499,0,0,0,0,0,7473,0
Number per km2,0,288,0,0,0,0,0,0
million miles,0,0,0,0,0,632,0,0

#data exploration

##Distribution of Air Quality Indicators

## in depth check for numircal columns

In [146]:
num_cols = df.select_dtypes(include="number").columns.drop(
    ["Unique ID", "Indicator ID", "Geo Join ID", "Message"]
)
num_cols

Index(['Data Value'], dtype='str')

In [147]:
px.histogram(
    df,
    x="Data Value",
    title="Distribution of Data Value"
).show()

px.box(
    df,
    x="Data Value",
    title="Box Plot of Data Value"
).show()

## in depth check for catagorical columns

In [148]:
cat_cols = df.select_dtypes(include="str").columns
cat_cols

Index(['Name', 'Measure', 'Measure Info', 'Geo Type Name', 'Geo Place Name',
       'Time Period', 'Start_Date'],
      dtype='str')

In [149]:
for col in cat_cols:
    px.histogram(
        data_frame=df,
        x=col,
        title=f"Distribution of {col}"
    ).show()

##Statistical Summary of PM2.5 Values

In [150]:
pm25 = df[df["Name"] == "Fine particles (PM 2.5)"]

pm25["Data Value"].describe()

count    5499.000000
mean        9.355528
std         2.041713
min         5.320000
25%         7.850000
50%         9.080000
75%        10.610000
max        18.840000
Name: Data Value, dtype: float64

##Distribution of PM2.5 Values

In [151]:
fig = px.histogram(
    pm25,
    x="Data Value",
    nbins=30,
    title="Distribution of PM2.5 Values"
)

fig.show()

##PM2.5 Distribution by Geographic Type

In [152]:
fig = px.box(
    pm25,
    x="Geo Type Name",
    y="Data Value",
    title="PM2.5 Distribution by Geographic Type"
)

fig.show()

#data cleaning

## Create Clean Dataset

In [207]:
df_clean = df.copy()

## Remove Completely Missing Column

In [208]:
df_clean = df_clean.drop(columns=["Message"])

## Convert Start Date

In [155]:
df_clean["Start_Date"] = pd.to_datetime(
    df_clean["Start_Date"],
    errors="coerce"
)

## Standardize Measurement Units

In [156]:
df_clean["Measure Info"] = df_clean["Measure Info"].replace(
    {"µg/m3": "mcg/m3"}
)

## Check Text Formatting

In [157]:
text_cols = df_clean.select_dtypes(include="str").columns

for col in text_cols:
    print(
        col,
        (df_clean[col] != df_clean[col].str.strip()).sum()
    )

Name 0
Measure 0
Measure Info 0
Geo Type Name 0
Geo Place Name 0
Time Period 0

## Final Data Quality Check

In [158]:
print("Shape:", df_clean.shape)

print("\nMissing values:")
print(df_clean.isnull().sum())

print("\nDuplicate rows:", df_clean.duplicated().sum())

print(
    "Duplicate Unique IDs:",
    df_clean["Unique ID"].duplicated().sum()
)

Shape: (16218, 11)

Missing values:
Unique ID         0
Indicator ID      0
Name              0
Measure           0
Measure Info      0
Geo Type Name     0
Geo Join ID       0
Geo Place Name    0
Time Period       0
Start_Date        0
Data Value        0
dtype: int64

Duplicate rows: 0
Duplicate Unique IDs: 0

#FEATURE ENGINEERING

In [168]:
df_clean["Start Year"] = df_clean["Start_Date"].dt.year

In [167]:
df_clean[["Start_Date", "Time Period", "Start Year"]].head(10)

  Start_Date          Time Period  Start Year
0 2010-12-01  Annual Average 2011        2010
1 2008-12-01  Annual Average 2009        2008
2 2015-01-01  Annual Average 2015        2015
3 2015-01-01  Annual Average 2015        2015
4 2008-12-01  Annual Average 2009        2008
5 2020-01-01  Annual Average 2020        2020
6 2008-12-01  Annual Average 2009        2008
7 2010-12-01  Annual Average 2011        2010
8 2010-12-01       Winter 2010-11        2010
9 2012-12-01  Annual Average 2013        2012

In [187]:
df_clean["Period Type"] = df_clean["Time Period"].apply(
    lambda x:
        "Summer" if x.startswith("Summer")
        else "Winter" if x.startswith("Winter")
        else "Annual" if x.startswith("Annual")
        else "Year/Range"
)

In [163]:
df_clean[["Time Period", "Period Type"]].drop_duplicates().head(20)

                         Time Period Period Type
0                Annual Average 2011      Annual
1                Annual Average 2009      Annual
2                Annual Average 2015      Annual
5                Annual Average 2020      Annual
8                     Winter 2010-11      Winter
9                Annual Average 2013      Annual
11                    Winter 2014-15      Winter
12               Annual Average 2021      Annual
14                       Summer 2009      Summer
19               Annual Average 2017      Annual
27                    Winter 2009-10      Winter
28                       Summer 2017      Summer
29                       Summer 2018      Summer
32                    Winter 2018-19      Winter
33                       Summer 2014      Summer
55                    Winter 2016-17      Winter
59               Annual Average 2014      Annual
63                    Winter 2011-12      Winter
94                       Summer 2020      Summer
576  2-Year Summer Average 2009-2010      Summer

In [165]:
df_clean["Is Multi-Year"] = df_clean["Time Period"].str.contains(
    r"\d{4}-\d{2,4}",
    regex=True
)

In [166]:
df_clean[["Time Period", "Start Year", "Period Type", "Is Multi-Year"]].drop_duplicates().head(20)

                         Time Period  Start Year Period Type  Is Multi-Year
0                Annual Average 2011        2010      Annual          False
1                Annual Average 2009        2008      Annual          False
2                Annual Average 2015        2015      Annual          False
5                Annual Average 2020        2020      Annual          False
8                     Winter 2010-11        2010      Winter           True
9                Annual Average 2013        2012      Annual          False
11                    Winter 2014-15        2014      Winter           True
12               Annual Average 2021        2021      Annual          False
14                       Summer 2009        2009      Summer          False
19               Annual Average 2017        2017      Annual          False
27                    Winter 2009-10        2009      Winter           True
28                       Summer 2017        2017      Summer          False
29                       Summer 2018        2018      Summer          False
32                    Winter 2018-19        2018      Winter           True
33                       Summer 2014        2014      Summer          False
55                    Winter 2016-17        2016      Winter           True
59               Annual Average 2014        2013      Annual          False
63                    Winter 2011-12        2011      Winter           True
94                       Summer 2020        2020      Summer          False
576  2-Year Summer Average 2009-2010        2009      Summer           True

#DATA ANALYSIS

##How do PM2.5 values vary across different geographic types?

In [169]:
pm25 = df_clean[df_clean["Name"] == "Fine particles (PM 2.5)"]

In [170]:
pm25.groupby("Geo Type Name")["Data Value"].agg(
    ["count", "mean", "median", "min", "max"]
).round(2)

               count  mean  median   min    max
Geo Type Name
Borough          195  9.21    8.96  5.54  15.34
CD              2301  9.40    9.12  5.32  18.84
Citywide          39  8.93    8.63  6.06  12.89
UHF34           1326  9.28    9.05  5.33  16.38
UHF42           1638  9.38    9.12  5.33  17.61

In [171]:
fig = px.box(
    pm25,
    x="Geo Type Name",
    y="Data Value",
    title="PM2.5 Values by Geographic Type"
)

fig.show()

##How do PM2.5 values change over time?

In [172]:
pm25.groupby("Start Year")["Data Value"].agg(
    ["count", "mean", "median", "min", "max"]
).round(2)

            count   mean  median   min    max
Start Year
2008          282  12.27   12.03  8.75  18.84
2009          423  10.53   10.38  7.94  16.03
2010          423  11.99   11.83  8.44  16.99
2011          423  10.30   10.29  6.72  15.55
2012          423  10.24   10.10  7.61  16.09
2013          423  10.78   10.46  7.69  17.44
2014          282   9.31    9.05  7.36  13.20
2015          564   8.78    8.75  5.92  13.07
2016          282   8.33    8.15  6.87  11.74
2017          423   8.56    8.39  6.32  12.61
2018          423   7.93    7.79  6.06  13.46
2019          423   7.71    7.55  5.59  12.55
2020          423   6.80    6.70  5.32   9.24
2021          282   7.69    7.79  5.92  10.94

In [180]:
fig = px.line(
    pm25.groupby("Start Year", as_index=False)["Data Value"].mean(),
    x="Start Year",
    y="Data Value",
    markers=True,
    text="Data Value",
    title="Average PM2.5 Values Over Time"
)

fig.update_traces(
    texttemplate="%{text:.2f}",
    textposition="top center"
)

fig.update_layout(
    xaxis_title="Start Year",
    yaxis_title="Average PM2.5"
)

fig.show()

##How do PM2.5 values vary by period type?

In [174]:
pm25.groupby("Period Type")["Data Value"].agg(
    ["count", "mean", "median", "min", "max"]
).round(2)

             count  mean  median   min    max
Period Type
Annual        1833  8.60    8.50  5.32  16.09
Summer        1833  9.67    9.59  6.27  16.12
Winter        1833  9.80    9.32  5.92  18.84

##Which geographic type shows the highest variability in PM2.5?

In [175]:
pm25.groupby("Geo Type Name")["Data Value"].agg(
    ["count", "mean", "std", "min", "max"]
).round(2)

               count  mean   std   min    max
Geo Type Name
Borough          195  9.21  1.95  5.54  15.34
CD              2301  9.40  2.06  5.32  18.84
Citywide          39  8.93  1.72  6.06  12.89
UHF34           1326  9.28  1.99  5.33  16.38
UHF42           1638  9.38  2.07  5.33  17.61

##How does PM2.5 vary across geographic types and period types?

In [176]:
pm25.groupby(
    ["Geo Type Name", "Period Type"]
)["Data Value"].mean().round(2).unstack()

Period Type    Annual  Summer  Winter
Geo Type Name
Borough          8.44    9.53    9.65
CD               8.64    9.70    9.86
Citywide         8.17    9.30    9.33
UHF34            8.52    9.61    9.72
UHF42            8.63    9.69    9.82

##Which PM2.5 geographic type has the highest average value over time?

In [177]:
pm25_year_geo = pm25.groupby(
    ["Start Year", "Geo Type Name"],
    as_index=False
)["Data Value"].mean()

pm25_year_geo.head()

   Start Year Geo Type Name  Data Value
0        2008       Borough   12.072000
1        2008            CD   12.348051
2        2008      Citywide   11.660000
3        2008         UHF34   12.157500
4        2008         UHF42   12.281190

In [178]:
fig = px.line(
    pm25_year_geo,
    x="Start Year",
    y="Data Value",
    color="Geo Type Name",
    markers=True,
    title="Average PM2.5 by Geographic Type Over Time"
)

fig.update_layout(
    xaxis_title="Start Year",
    yaxis_title="Average PM2.5"
)

fig.show()

In [181]:
import streamlit as st

In [209]:
df_clean.head(15)

,Unique ID,Indicator ID,Name,Measure,Measure Info,Geo Type Name,Geo Join ID,Geo Place Name,Time Period,Start_Date,Data Value
0,172653,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,203,Bedford Stuyvesant - Crown Heights,Annual Average 2011,12/1/2010,25.30
1,172585,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,203,Bedford Stuyvesant - Crown Heights,Annual Average 2009,12/1/2008,26.93
2,336637,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,204,East New York,Annual Average 2015,1/1/2015,19.09
3,336622,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,103,Fordham - Bronx Pk,Annual Average 2015,1/1/2015,19.76
4,172582,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,104,Pelham - Throgs Neck,Annual Average 2009,12/1/2008,22.83
5,667327,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,104,Pelham - Throgs Neck,Annual Average 2020,1/1/2020,16.19
6,172607,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,306308,Chelsea-Village,Annual Average 2009,12/1/2008,38.16
7,172675,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,306308,Chelsea-Village,Annual Average 2011,12/1/2010,34.96
8,175345,375,Nitrogen dioxide (NO2),Mean,ppb,UHF42,206,Borough Park,Winter 2010-11,12/1/2010,30.10
9,176689,375,Nitrogen dioxide (NO2),Mean,ppb,UHF42,206,Borough Park,Annual Average 2013,12/1/2012,20.23
10,176682,375,Nitrogen dioxide (NO2),Mean,ppb,UHF42,106,High Bridge - Morrisania,Annual Average 2013,12/1/2012,23.73
11,336507,375,Nitrogen dioxide (NO2),Mean,ppb,UHF42,106,High Bridge - Morrisania,Winter 2014-15,12/1/2014,26.00
12,740910,375,Nitrogen dioxide (NO2),Mean,ppb,UHF42,106,High Bridge - Morrisania,Annual Average 2021,1/1/2021,18.04
13,175348,375,Nitrogen dioxide (NO2),Mean,ppb,UHF42,209,Bensonhurst - Bay Ridge,Winter 2010-11,12/1/2010,28.44
14,175894,375,Nitrogen dioxide (NO2),Mean,ppb,UHF42,209,Bensonhurst - Bay Ridge,Summer 2009,6/1/2009,18.95

In [188]:
df_clean["Period Type"].value_counts()

Period Type
Summer        5499
Annual        3666
Winter        3666
Year/Range    3387
Name: count, dtype: int64

#save cleaned data frame

In [210]:
df_clean.to_parquet("Air_Quality_Cleaned.parquet")

In [211]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 16218 entries, 0 to 16217
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unique ID       16218 non-null  int64
 1   Indicator ID    16218 non-null  int64
 2   Name            16218 non-null  str
 3   Measure         16218 non-null  str
 4   Measure Info    16218 non-null  str
 5   Geo Type Name   16218 non-null  str
 6   Geo Join ID     16218 non-null  int64
 7   Geo Place Name  16218 non-null  str
 8   Time Period     16218 non-null  str
 9   Start_Date      16218 non-null  str
 10  Data Value      16218 non-null  float64
dtypes: float64(1), int64(3), str(7)
memory usage: 2.7 MB